[project]
name = "git-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "folgaa", email = "fuga_olga@mail.ru" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
git-uv = "git_uv:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.9",
    "ty>=0.0.84",
]
